---
- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Copy custom apache config files
      copy:
        src: ./conf/default.conf
        dest: /etc/apache2/sites-available/default.conf
        owner: root
        group: root
        mode: 0644


    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes
