---
- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Stop Apache
      service: "name=apache2 state=stopped"

    - name: Uninstall Apache
      apt: "name=apache2 state=absent"

