---
- hosts: all
  become: yes
  gather_facts: true

  tasks:

    # Install and configure Apache on RHEL/CentOS hosts.
    - block:
        - name: Install Apache on CentOS
          yum:
            name: httpd
            state: present
            update_cache: yes 


        - name: Start and enable Apache service
          service:
            name: httpd
            state: started
            enabled: yes
      when: ansible_os_family == 'RedHat'


    # Install and configure Apache on Debian/Ubuntu hosts.
    - block:
        - name: Install Apache on Ubuntu
          apt:
            name: apache2
            state: present
            update_cache: yes

        - name: Copy custom apache config files
          copy:
            src: ./conf/default.conf
            dest: /etc/apache2/sites-available/default.conf
            owner: root
            group: root
            mode: 0644

        - name: Start and enable Apache service
          service:
            name: apache2
            state: started
            enabled: yes
      when: ansible_os_family == 'Debian'
