---
- hosts: all
  become: yes
  gather_facts: true

  vars_files:
    - vars/default.yml

  pre_tasks:
    - name: update cache if needed
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

  tasks:
    - name: Add php repositories for newer php versions.
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: Install Apache, MySQL, PHP and other dependancies
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - python3-pymysql
        state: present

    - name: Ensure path exists for wordpress.
      file:
        path: /var/www/html/
        state: directory
        owner: www-data
        group: www-data

    - name: Download wordpress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Setup wordpress configuration
      template:
        src: files/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

    - name: Copy Apache config file.
      copy:
        src: files/default.conf
        dest: /etc/apache2/sites-enabled/default.conf
      notify: restart apache

    - name: Remove default virtualhost file.
      file:
        path: "/etc/apache2/sites-enabled/000-default.conf"
        state: absent
      notify: restart apache

    - name: Create a MySQL database for wordpress.
      mysql_db:
        db: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create a MySQL user for wordpress.
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Start Apache, MySQL, and PHP
      service: "name={{ item }} state=started enabled=yes"
      with_items:
          - apache2
          - mysql
